global:
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'expense_tracker'
    scrape_interval: 5s
    static_configs:
      - targets: ['expense-tracker-dev-env-backend-1:8080']
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['expense-tracker-dev-env-prometheus-1:9090']
  
    
